name: Python Data Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run autolysis script on all CSV files
      env:
        AIPROXY_TOKEN: ${{ secrets.AIPROXY_TOKEN }}
      run: |
        for file in *.csv; do
          echo "Processing $file"
          python autolysis.py "$file"
        done

    - name: List generated files
      run: |
        echo "Generated Files:"
        find . -type f

    - name: Upload generated files
      uses: actions/upload-artifact@v4
      with:
        name: generated-files
        path: |
          **/README.md
          **/*.png
        if-no-files-found: warn
        include-hidden-files: false
