name: Python Data Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install openai  # Install the openai library directly
        pip install -r requirements.txt  # This will install other dependencies if you still use them

    - name: Run autolysis script on all CSV files
      env:
        AIPROXY_TOKEN: ${{ secrets.AIPROXY_TOKEN }}  # Access secret token securely
      run: |
        for file in *.csv; do
          echo "Processing $file"
          python autolysis.py "$file"  # Run your Python script on each CSV file
        done

    - name: Upload generated files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: analysis-artifacts
        path: |
          '*.png'  # Upload PNG files (charts)
          '*.md'   # Upload README files
